#   This file is part of Revoke-Obfuscation.
#
#   Copyright 2017 Daniel Bohannon <@danielhbohannon>
#         while at Mandiant <http://www.mandiant.com>
#         and Lee Holmes <@Lee_Holmes>
#         while at Microsoft <https://www.microsoft.com>
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.



#
# Module manifest for module 'Revoke-Obfuscation'
#
# Generated by: Daniel Bohannon (@danielhbohannon)
#
# Generated on: 2017-05-23
#



@{

# Script module or binary module file associated with this manifest.
RootModule = 'Revoke-Obfuscation.psm1'

# Version number of this module.
ModuleVersion = '1.1'

# ID used to uniquely identify this module
GUID = 'a0a9150d-a6a4-ad17-f325-a3a24fed0aa9'

# Author of this module
Author = 'Daniel Bohannon (@danielhbohannon)'

# Copyright statement for this module
Copyright = 'Apache License, Version 2.0'

# Description of the functionality provided by this module
Description = 'PowerShell module file for importing all required modules for the Revoke-Obfuscation framework.'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '3.0'

# Minimum version of the Windows PowerShell host required by this module
PowerShellHostVersion = '1.6'

# Script files (.ps1) that are run in the caller's environment prior to importing this module
#ScriptsToProcess = @('Get-ScriptBlock.ps1')
ScriptsToProcess = @()

# Functions to export from this module
FunctionsToExport = 'Measure-RvoObfuscation','Get-RvoFeatureVector','Get-RvoScriptBlock','Update-RvoWhitelist','Revoke-Obfuscation'

FormatsToProcess = 'format.ps1xml'

# HelpInfo URI of this module
# HelpInfoURI = ''

}